"""Tests for issue #89: Rounded rectangle corners in EasyEDA footprints.

Uses real component data from the issue report to verify that SOLIDREGION shapes
with SVG arc commands produce correct rounded corner geometry instead of
distorted straight-line polygons.

Layer mapping tested here:
  - Layer 11 npth SOLIDREGION → Edge.Cuts (board window cutout for back-mount LEDs)
  - Layer 12 solid SOLIDREGION → F.Fab (pad-edge markers, polarity indicators)
  - Layer 3 solid SOLIDREGION  → F.SilkS (silkscreen fill indicators)

Visual comparison SVGs are regenerated by test_generate_visual_comparisons()
into tests/visual/ for manual inspection.
"""

import json
import math
from pathlib import Path

import pytest

from kicad_jlcimport.easyeda.parser import (
    _parse_svg_path_with_arcs,
    _parse_svg_polygon,
    mil_to_mm,
    parse_footprint_shapes,
)
from kicad_jlcimport.kicad.footprint_writer import write_footprint

TESTDATA = Path(__file__).parent.parent / "testdata"


def _load_footprint(part_id):
    """Load footprint shapes and origin from testdata JSON."""
    with open(TESTDATA / f"{part_id}_footprint.json") as f:
        data = json.load(f)
    ds = data["dataStr"]
    return ds["shape"], ds["head"]["x"], ds["head"]["y"]


def _find_npth_svg(shapes):
    """Extract the SVG path string from the NPTH SOLIDREGION in a shape list."""
    for s in shapes:
        parts = s.split("~")
        if parts[0] != "SOLIDREGION":
            continue
        svg_path = ""
        rtype = "solid"
        for p in parts[2:]:
            p = p.strip()
            if p.startswith("M") and len(p) > 1 and (p[1].isdigit() or p[1] in " \t-"):
                svg_path = p
            elif p in ("npth", "solid", "cutout"):
                rtype = p
        if rtype == "npth" and svg_path:
            return svg_path
    return None


# ---------------------------------------------------------------------------
# C3646936 — 1206 SMD LED (orange), layer-11 body fill between pads
# ---------------------------------------------------------------------------
class TestC3646936BodyFill:
    """C3646936: XL-3216UOC-FB — layer 11 npth board cutout + rounded corners.

    This is a reverse-mount (bottom-mount) LED.  The layer-11 NPTH SOLIDREGION
    is the board window cutout through which the LED shines, and must land on
    Edge.Cuts with arc-interpolated rounded corners.
    """

    @pytest.fixture(autouse=True)
    def setup(self):
        self.shapes, self.ox, self.oy = _load_footprint("C3646936")
        self.npth_svg = _find_npth_svg(self.shapes)

    def test_has_npth_arc_shape(self):
        """The raw data must contain an NPTH SOLIDREGION with arc commands."""
        assert self.npth_svg is not None
        assert "A" in self.npth_svg

    def test_old_parser_loses_corners(self):
        """_parse_svg_polygon (straight-line only) must drop the arc points."""
        old_pts = _parse_svg_polygon(self.npth_svg)
        assert len(old_pts) == 4, f"Expected 4 straight-line points, got {len(old_pts)}"

    def test_arc_parser_preserves_corners(self):
        """_parse_svg_path_with_arcs must interpolate each arc corner."""
        new_pts = _parse_svg_path_with_arcs(self.npth_svg)
        assert len(new_pts) >= 20, f"Expected ≥20 arc-interpolated points, got {len(new_pts)}"

    def test_board_cutout_on_edge_cuts(self):
        """Layer-11 npth SOLIDREGION must land on Edge.Cuts (board window cutout)."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        edge_cuts = [r for r in fp.regions if r.layer == "Edge.Cuts"]
        assert len(edge_cuts) == 1, "Expected exactly one Edge.Cuts region for the board cutout"
        assert edge_cuts[0].region_type == "npth"

    def test_cutout_inside_pad_extents(self):
        """The board window sits between the pads (x-extent < pad x-extent)."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        region = next(r for r in fp.regions if r.layer == "Edge.Cuts")
        xs = [pt[0] for pt in region.points]
        body_half_x = (max(xs) - min(xs)) / 2
        pad_half_x = max(abs(p.x) + p.width / 2 for p in fp.pads)
        assert body_half_x < pad_half_x, (
            f"Cutout x half-extent ({body_half_x:.3f}mm) must be less than pad x half-extent ({pad_half_x:.3f}mm)"
        )

    def test_cutout_bounding_box(self):
        """Board window should be approximately 2.2 × 1.9 mm."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        region = next(r for r in fp.regions if r.layer == "Edge.Cuts")
        xs = [pt[0] for pt in region.points]
        ys = [pt[1] for pt in region.points]
        width = max(xs) - min(xs)
        height = max(ys) - min(ys)
        assert abs(width - 2.2) < 0.05, f"Expected ~2.2mm width, got {width:.4f}mm"
        assert abs(height - 1.9) < 0.05, f"Expected ~1.9mm height, got {height:.4f}mm"

    def test_corners_are_rounded(self):
        """Arc-interpolated points must lie on the corner arc, not a straight line."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        region = next(r for r in fp.regions if r.layer == "Edge.Cuts")
        pts = region.points
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        cx = (max(xs) + min(xs)) / 2
        cy = (max(ys) + min(ys)) / 2
        half_w = (max(xs) - min(xs)) / 2
        half_h = (max(ys) - min(ys)) / 2

        # Arc centre for top-right corner is inset from the outer corner by r
        # in both axes independently (handles non-square shapes correctly).
        expected_radius = mil_to_mm(0.7874)
        corner_cx = cx + (half_w - expected_radius)
        corner_cy = cy - (half_h - expected_radius)

        corner_pts = [
            p
            for p in pts
            if p[0] > cx + (half_w - expected_radius) * 0.5 and p[1] < cy - (half_h - expected_radius) * 0.5
        ]
        assert len(corner_pts) >= 4, "Expected several arc-interpolated points in top-right corner"
        for px, py in corner_pts:
            dist = math.sqrt((px - corner_cx) ** 2 + (py - corner_cy) ** 2)
            assert abs(dist - expected_radius) < 0.01, (
                f"Point ({px:.4f},{py:.4f}) is {dist:.4f}mm from corner centre, expected {expected_radius:.4f}mm"
            )

    def test_has_two_pads(self):
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        assert len(fp.pads) == 2

    def test_fab_polarity_markers(self):
        """Layer-12 solid regions (pad-edge markers) must appear on F.Fab."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        fab_solid = [r for r in fp.regions if r.layer == "F.Fab" and r.region_type == "solid"]
        assert len(fab_solid) >= 2, "Expected ≥2 F.Fab solid regions for polarity markers"

    def test_kicad_output_contains_edge_cuts_poly(self):
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        content = write_footprint(fp, "C3646936")
        assert "fp_poly" in content
        assert '"Edge.Cuts"' in content


# ---------------------------------------------------------------------------
# C3646937 — 1206 SMD LED (green) with slot region, spaceless SVG arcs
# ---------------------------------------------------------------------------
class TestC3646937SlotRegion:
    """C3646937: XL-3216UGC-FB — layer-11 board cutout + spaceless SVG arc format.

    This reverse-mount LED uses a compact SVG notation with no spaces between
    commands (e.g. "2996.8504L3995.6693").  It also has several F.Fab solid
    regions with small arcs (corner radii 0.1575 units) forming a complex body
    outline shape.
    """

    @pytest.fixture(autouse=True)
    def setup(self):
        self.shapes, self.ox, self.oy = _load_footprint("C3646937")
        self.npth_svg = _find_npth_svg(self.shapes)

    def test_has_npth_arc_shape(self):
        assert self.npth_svg is not None
        assert "A" in self.npth_svg

    def test_spaceless_format_present(self):
        """Verify the raw data actually uses the spaceless 'coordLcoord' format."""
        # Either spaceless or spaced — both are valid; spaceless is the specific
        # regression case for this part.
        has_spaceless = "L3" in self.npth_svg or "L4" in self.npth_svg
        has_spaced = " L " in self.npth_svg
        assert has_spaceless or has_spaced, "Expected L commands in the NPTH path"

    def test_old_parser_loses_corners(self):
        old_pts = _parse_svg_polygon(self.npth_svg)
        assert len(old_pts) <= 6, f"Expected ≤6 straight-line points, got {len(old_pts)}"

    def test_arc_parser_preserves_corners(self):
        new_pts = _parse_svg_path_with_arcs(self.npth_svg)
        assert len(new_pts) >= 20

    def test_board_cutout_on_edge_cuts(self):
        """Layer-11 npth must land on Edge.Cuts (board window cutout)."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        edge_cuts = [r for r in fp.regions if r.layer == "Edge.Cuts"]
        assert len(edge_cuts) == 1
        assert edge_cuts[0].region_type == "npth"

    def test_cutout_inside_pad_extents(self):
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        region = next(r for r in fp.regions if r.layer == "Edge.Cuts")
        xs = [pt[0] for pt in region.points]
        body_half_x = (max(xs) - min(xs)) / 2
        pad_half_x = max(abs(p.x) + p.width / 2 for p in fp.pads)
        assert body_half_x < pad_half_x

    def test_cutout_bounding_box(self):
        """Board window should be approximately 2.2 × 1.8 mm."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        region = next(r for r in fp.regions if r.layer == "Edge.Cuts")
        xs = [pt[0] for pt in region.points]
        ys = [pt[1] for pt in region.points]
        width = max(xs) - min(xs)
        height = max(ys) - min(ys)
        assert abs(width - 2.2) < 0.05, f"Expected ~2.2mm width, got {width:.4f}mm"
        assert abs(height - 1.8) < 0.05, f"Expected ~1.8mm height, got {height:.4f}mm"

    def test_triangle_indicator_on_silk_and_fab(self):
        """The play-button triangle must be present on both F.SilkS and F.Fab."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        silk_tris = [r for r in fp.regions if r.layer == "F.SilkS" and len(r.points) == 3]
        fab_tris = [r for r in fp.regions if r.layer == "F.Fab" and len(r.points) == 3]
        assert len(silk_tris) >= 1, "Expected triangle region on F.SilkS"
        assert len(fab_tris) >= 1, "Expected triangle region on F.Fab"

    def test_fab_regions_with_arc_geometry(self):
        """C3646937 has F.Fab solid SOLIDREGIONs with small arc corners."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        fab_arc_regions = [
            r for r in fp.regions if r.layer == "F.Fab" and r.region_type == "solid" and len(r.points) > 4
        ]
        assert len(fab_arc_regions) >= 1, "Expected ≥1 arc-geometry F.Fab solid region"

    def test_has_two_pads(self):
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        assert len(fp.pads) == 2

    def test_kicad_output_has_edge_cuts_poly(self):
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        content = write_footprint(fp, "C3646937")
        assert "fp_poly" in content
        assert '"Edge.Cuts"' in content


# ---------------------------------------------------------------------------
# C3646938 — back-mounted LED (original issue #89 example)
# ---------------------------------------------------------------------------
class TestC3646938RoundedRect:
    """C3646938: four rounded corners, each a 0.7874-unit-radius arc.

    Original issue #89 example: back-mounted LED, layer-11 npth maps to Edge.Cuts.
    """

    @pytest.fixture(autouse=True)
    def setup(self):
        self.shapes, self.ox, self.oy = _load_footprint("C3646938")
        self.npth_svg = _find_npth_svg(self.shapes)

    def test_npth_shape_has_arc_commands(self):
        """The raw SVG path must contain arc (A) commands."""
        assert self.npth_svg is not None
        assert "A" in self.npth_svg

    def test_old_parser_loses_corners(self):
        """_parse_svg_polygon (the old code path) produces only 4 points — no arcs."""
        old_points = _parse_svg_polygon(self.npth_svg)
        assert len(old_points) == 4

    def test_arc_parser_preserves_corners(self):
        """_parse_svg_path_with_arcs produces many points for the 4 corner arcs."""
        new_points = _parse_svg_path_with_arcs(self.npth_svg)
        assert len(new_points) >= 20

    def test_full_parse_produces_edge_cuts_region(self):
        """Layer-11 npth SOLIDREGION must land on Edge.Cuts with rounded corners."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        edge_cuts = [r for r in fp.regions if r.layer == "Edge.Cuts"]
        assert len(edge_cuts) == 1
        assert edge_cuts[0].region_type == "npth"
        assert len(edge_cuts[0].points) >= 20

    def test_bounding_box_is_square(self):
        """The rounded rectangle should be ~2mm × 2mm (centered)."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        region = next(r for r in fp.regions if r.layer == "Edge.Cuts")
        xs = [p[0] for p in region.points]
        ys = [p[1] for p in region.points]
        width = max(xs) - min(xs)
        height = max(ys) - min(ys)
        assert abs(width - 2.0) < 0.01, f"Expected ~2.0mm width, got {width:.4f}"
        assert abs(height - 2.0) < 0.01, f"Expected ~2.0mm height, got {height:.4f}"

    def test_corners_are_rounded(self):
        """Points along each corner arc must lie on a circle of the expected radius."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        region = next(r for r in fp.regions if r.layer == "Edge.Cuts")
        pts = region.points
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        half_w = (max(xs) - min(xs)) / 2
        cx = (max(xs) + min(xs)) / 2
        cy = (max(ys) + min(ys)) / 2

        expected_radius = mil_to_mm(0.7874)
        inner = half_w - expected_radius

        corner_pts = [p for p in pts if p[0] > cx + inner * 0.5 and p[1] < cy - inner * 0.5]
        assert len(corner_pts) >= 4, "Expected several arc points in top-right corner"
        for px, py in corner_pts:
            dist = math.sqrt((px - (cx + inner)) ** 2 + (py - (cy - inner)) ** 2)
            assert abs(dist - expected_radius) < 0.01, (
                f"Point ({px:.4f},{py:.4f}) is {dist:.4f}mm from corner centre, expected {expected_radius:.4f}mm"
            )

    def test_kicad_output_not_empty(self):
        """write_footprint should produce valid KiCad output with the region."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        content = write_footprint(fp, "C3646938")
        assert "fp_poly" in content
        assert '"Edge.Cuts"' in content


# ---------------------------------------------------------------------------
# Visual comparison SVG generator (run with pytest -s to see output paths)
# ---------------------------------------------------------------------------
class TestGenerateVisualComparisons:
    """Generate before/after SVGs for visual inspection.

    Run with: pytest tests/test_issue89_rounded_corners.py -k visual -s
    """

    def test_generate_visual_comparisons(self):
        """Produce overlay SVGs: red dashed = old (buggy), green solid = fixed."""
        visual_dir = Path(__file__).parent / "visual"
        visual_dir.mkdir(exist_ok=True)

        for part in ["C3646936", "C3646937", "C3646938"]:
            shapes, ox, oy = _load_footprint(part)
            npth_svg = _find_npth_svg(shapes)
            assert npth_svg is not None

            ox_mm, oy_mm = mil_to_mm(ox), mil_to_mm(oy)
            new_pts = [(x - ox_mm, y - oy_mm) for x, y in _parse_svg_path_with_arcs(npth_svg)]
            old_pts = [(x - ox_mm, y - oy_mm) for x, y in _parse_svg_polygon(npth_svg)]

            svg = _build_comparison_svg(part, new_pts, old_pts)
            out = visual_dir / f"{part}_npth_comparison.svg"
            out.write_text(svg)
            print(f"  Wrote {out}")

        for part in ["C3646936", "C3646937", "C3646938"]:
            shapes, ox, oy = _load_footprint(part)
            fp = parse_footprint_shapes(shapes, ox, oy)
            content = write_footprint(fp, part)
            out = visual_dir / f"{part}.kicad_mod"
            out.write_text(content)
            print(f"  Wrote {out}")


def _build_comparison_svg(part, new_pts, old_pts, width=400, height=400):
    """Build an SVG overlaying old (red dashed) and new (green solid) polygons."""
    all_pts = new_pts + old_pts
    xs = [p[0] for p in all_pts]
    ys = [p[1] for p in all_pts]
    margin = 0.2
    min_x, max_x = min(xs) - margin, max(xs) + margin
    min_y, max_y = min(ys) - margin, max(ys) + margin
    vw = max_x - min_x
    vh = max_y - min_y
    scale = min(width / vw, height / vh) * 0.8

    def tx(x):
        return (x - min_x) * scale + (width - vw * scale) / 2

    def ty(y):
        return (y - min_y) * scale + (height - vh * scale) / 2

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}"'
        f' viewBox="0 0 {width} {height}" style="background:#1a1a2e;">',
        f'<text x="{width / 2}" y="25" text-anchor="middle" fill="white"'
        f' font-family="monospace" font-size="14">{part}: NPTH Edge.Cuts board window</text>',
    ]

    if old_pts:
        d = "M " + " L ".join(f"{tx(x):.1f},{ty(y):.1f}" for x, y in old_pts) + " Z"
        lines.append(
            f'<path d="{d}" fill="rgba(255,68,68,0.15)" stroke="#ff4444" stroke-width="2" stroke-dasharray="6,4"/>'
        )

    if new_pts:
        d = "M " + " L ".join(f"{tx(x):.1f},{ty(y):.1f}" for x, y in new_pts) + " Z"
        lines.append(f'<path d="{d}" fill="rgba(68,255,68,0.1)" stroke="#44ff44" stroke-width="2"/>')

    for x, y in new_pts:
        lines.append(f'<circle cx="{tx(x):.1f}" cy="{ty(y):.1f}" r="2" fill="#44ff44" opacity="0.6"/>')
    for x, y in old_pts:
        lines.append(f'<circle cx="{tx(x):.1f}" cy="{ty(y):.1f}" r="4" fill="#ff4444" opacity="0.8"/>')

    ly = height - 40
    lines.append(
        f'<line x1="20" y1="{ly}" x2="50" y2="{ly}" stroke="#ff4444" stroke-width="2" stroke-dasharray="6,4"/>'
    )
    lines.append(
        f'<text x="55" y="{ly + 4}" fill="#ff4444" font-family="monospace"'
        f' font-size="11">Before fix ({len(old_pts)} pts)</text>'
    )
    lines.append(f'<line x1="20" y1="{ly + 18}" x2="50" y2="{ly + 18}" stroke="#44ff44" stroke-width="2"/>')
    lines.append(
        f'<text x="55" y="{ly + 22}" fill="#44ff44" font-family="monospace"'
        f' font-size="11">After fix ({len(new_pts)} pts)</text>'
    )
    lines.append("</svg>")
    return "\n".join(lines)
