"""Tests for issue #89: Rounded rectangle corners in EasyEDA footprints.

Uses real component data from the issue report (C3646938, C3646937) to verify
that NPTH SOLIDREGION shapes with SVG arc commands produce correct rounded
corner geometry instead of distorted straight-line polygons.

Visual comparison SVGs are regenerated by test_generate_visual_comparisons()
into tests/visual/ for manual inspection.
"""

import json
import math
from pathlib import Path

import pytest

from kicad_jlcimport.easyeda.parser import (
    _parse_svg_path_with_arcs,
    _parse_svg_polygon,
    mil_to_mm,
    parse_footprint_shapes,
)
from kicad_jlcimport.kicad.footprint_writer import write_footprint

TESTDATA = Path(__file__).parent.parent / "testdata"


def _load_footprint(part_id):
    """Load footprint shapes and origin from testdata JSON."""
    with open(TESTDATA / f"{part_id}_footprint.json") as f:
        data = json.load(f)
    ds = data["dataStr"]
    return ds["shape"], ds["head"]["x"], ds["head"]["y"]


def _find_npth_svg(shapes):
    """Extract the SVG path string from the NPTH SOLIDREGION in a shape list."""
    for s in shapes:
        parts = s.split("~")
        if parts[0] != "SOLIDREGION":
            continue
        svg_path = ""
        rtype = "solid"
        for p in parts[2:]:
            p = p.strip()
            if p.startswith("M") and len(p) > 1 and (p[1].isdigit() or p[1] in " \t-"):
                svg_path = p
            elif p in ("npth", "solid", "cutout"):
                rtype = p
        if rtype == "npth" and svg_path:
            return svg_path
    return None


# ---------------------------------------------------------------------------
# C3646938 — back-mounted LED with rounded rectangle NPTH outline
# ---------------------------------------------------------------------------
class TestC3646938RoundedRect:
    """C3646938: four rounded corners, each a 0.7874-unit-radius arc."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.shapes, self.ox, self.oy = _load_footprint("C3646938")
        self.npth_svg = _find_npth_svg(self.shapes)

    def test_npth_shape_has_arc_commands(self):
        """The raw SVG path must contain arc (A) commands."""
        assert self.npth_svg is not None
        assert "A" in self.npth_svg

    def test_old_parser_loses_corners(self):
        """_parse_svg_polygon (the old code path) produces only 4 points — no arcs."""
        old_points = _parse_svg_polygon(self.npth_svg)
        assert len(old_points) == 4

    def test_arc_parser_preserves_corners(self):
        """_parse_svg_path_with_arcs produces many points for the 4 corner arcs."""
        new_points = _parse_svg_path_with_arcs(self.npth_svg)
        # 4 line endpoints + 4 arcs × 8 segments each = ~36 points
        assert len(new_points) >= 20

    def test_full_parse_produces_edge_cuts_region(self):
        """parse_footprint_shapes should produce an Edge.Cuts region with rounded corners."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        edge_cuts = [r for r in fp.regions if r.layer == "Edge.Cuts"]
        assert len(edge_cuts) == 1
        region = edge_cuts[0]
        assert region.region_type == "npth"
        # Must have arc-interpolated points, not just 4
        assert len(region.points) >= 20

    def test_bounding_box_is_square(self):
        """The rounded rectangle should be ~2mm × 2mm (centered)."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        edge_cuts = [r for r in fp.regions if r.layer == "Edge.Cuts"][0]
        xs = [p[0] for p in edge_cuts.points]
        ys = [p[1] for p in edge_cuts.points]
        width = max(xs) - min(xs)
        height = max(ys) - min(ys)
        assert abs(width - 2.0) < 0.01, f"Expected ~2.0mm width, got {width:.4f}"
        assert abs(height - 2.0) < 0.01, f"Expected ~2.0mm height, got {height:.4f}"

    def test_corners_are_rounded(self):
        """Points along each corner arc should lie on a circle, not a straight line.

        For a properly rounded corner, all interpolated points between two
        straight edges should satisfy: distance_to_corner_center ≈ radius.
        """
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        edge_cuts = [r for r in fp.regions if r.layer == "Edge.Cuts"][0]
        pts = edge_cuts.points

        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        # The rounded rect is centered near origin; corner centers are at
        # (±inner, ±inner) where inner = half_size - radius
        half_w = (max(xs) - min(xs)) / 2
        cx = (max(xs) + min(xs)) / 2
        cy = (max(ys) + min(ys)) / 2

        # Radius: 0.7874 EE units = 0.7874 / 3.937 ≈ 0.2 mm
        expected_radius = mil_to_mm(0.7874)
        inner = half_w - expected_radius

        # Check top-right corner (center ≈ (cx+inner, cy-inner))
        corner_cx = cx + inner
        corner_cy = cy - inner
        corner_pts = [p for p in pts if p[0] > cx + inner * 0.5 and p[1] < cy - inner * 0.5]
        assert len(corner_pts) >= 4, "Expected several arc points in top-right corner"
        for px, py in corner_pts:
            dist = math.sqrt((px - corner_cx) ** 2 + (py - corner_cy) ** 2)
            assert abs(dist - expected_radius) < 0.01, (
                f"Point ({px:.4f},{py:.4f}) is {dist:.4f}mm from corner center, expected {expected_radius:.4f}mm"
            )

    def test_kicad_output_not_empty(self):
        """write_footprint should produce valid KiCad output with the region."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        content = write_footprint(fp, "C3646938")
        assert "fp_poly" in content
        assert "Edge.Cuts" in content


# ---------------------------------------------------------------------------
# C3646937 — LED with rounded rect NPTH + slot region (more severe breakage)
# ---------------------------------------------------------------------------
class TestC3646937SlotRegion:
    """C3646937: rounded NPTH + spaceless SVG format (no spaces between commands)."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.shapes, self.ox, self.oy = _load_footprint("C3646937")
        self.npth_svg = _find_npth_svg(self.shapes)

    def test_npth_shape_has_arc_commands(self):
        assert self.npth_svg is not None
        assert "A" in self.npth_svg

    def test_spaceless_format_parsed(self):
        """C3646937's NPTH has spaceless transitions like '2996.8504L3995.6693'.

        The arc-aware tokenizer must handle this correctly.
        """
        # Verify the spaceless format is actually present in the raw data
        assert "L3995.6693" in self.npth_svg or "L 3995.6693" in self.npth_svg

    def test_old_parser_loses_corners(self):
        old_points = _parse_svg_polygon(self.npth_svg)
        assert len(old_points) <= 6  # Only M/L endpoints, arcs lost

    def test_arc_parser_preserves_corners(self):
        new_points = _parse_svg_path_with_arcs(self.npth_svg)
        assert len(new_points) >= 20

    def test_full_parse_produces_edge_cuts(self):
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        edge_cuts = [r for r in fp.regions if r.layer == "Edge.Cuts"]
        assert len(edge_cuts) == 1
        region = edge_cuts[0]
        assert len(region.points) >= 20

    def test_bounding_box_dimensions(self):
        """The outline should be ~2.2mm × 1.8mm."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        edge_cuts = [r for r in fp.regions if r.layer == "Edge.Cuts"][0]
        xs = [p[0] for p in edge_cuts.points]
        ys = [p[1] for p in edge_cuts.points]
        width = max(xs) - min(xs)
        height = max(ys) - min(ys)
        assert abs(width - 2.2) < 0.02, f"Expected ~2.2mm width, got {width:.4f}"
        assert abs(height - 1.8) < 0.02, f"Expected ~1.8mm height, got {height:.4f}"

    def test_fab_regions_with_arcs(self):
        """C3646937 has F.Fab SOLIDREGION shapes with arc commands too."""
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        fab_regions = [r for r in fp.regions if r.layer == "F.Fab"]
        # At least one should have arc-interpolated points (> 4)
        arc_regions = [r for r in fab_regions if len(r.points) > 4]
        assert len(arc_regions) >= 1, "Expected at least one F.Fab region with arcs"

    def test_kicad_output_has_edge_cuts_poly(self):
        fp = parse_footprint_shapes(self.shapes, self.ox, self.oy)
        content = write_footprint(fp, "C3646937")
        assert "Edge.Cuts" in content
        assert "fp_poly" in content


# ---------------------------------------------------------------------------
# Visual comparison SVG generator (run with pytest -s to see output paths)
# ---------------------------------------------------------------------------
class TestGenerateVisualComparisons:
    """Generate before/after SVGs for visual inspection.

    Run with: pytest tests/test_issue89_rounded_corners.py -k visual -s
    """

    def test_generate_visual_comparisons(self):
        """Produce overlay SVGs: red dashed = old (buggy), green solid = fixed."""
        visual_dir = Path(__file__).parent / "visual"
        visual_dir.mkdir(exist_ok=True)

        for part in ["C3646938", "C3646937"]:
            shapes, ox, oy = _load_footprint(part)
            npth_svg = _find_npth_svg(shapes)
            assert npth_svg is not None

            ox_mm, oy_mm = mil_to_mm(ox), mil_to_mm(oy)
            new_pts = [(x - ox_mm, y - oy_mm) for x, y in _parse_svg_path_with_arcs(npth_svg)]
            old_pts = [(x - ox_mm, y - oy_mm) for x, y in _parse_svg_polygon(npth_svg)]

            svg = _build_comparison_svg(part, new_pts, old_pts)
            out = visual_dir / f"{part}_npth_comparison.svg"
            out.write_text(svg)
            print(f"  Wrote {out}")

        # Also generate full footprint KiCad files for opening in KiCad
        for part in ["C3646938", "C3646937"]:
            shapes, ox, oy = _load_footprint(part)
            fp = parse_footprint_shapes(shapes, ox, oy)
            content = write_footprint(fp, part)
            out = visual_dir / f"{part}.kicad_mod"
            out.write_text(content)
            print(f"  Wrote {out}")


def _build_comparison_svg(part, new_pts, old_pts, width=400, height=400):
    """Build an SVG overlaying old (red dashed) and new (green solid) polygons."""
    all_pts = new_pts + old_pts
    xs = [p[0] for p in all_pts]
    ys = [p[1] for p in all_pts]
    margin = 0.2
    min_x, max_x = min(xs) - margin, max(xs) + margin
    min_y, max_y = min(ys) - margin, max(ys) + margin
    vw = max_x - min_x
    vh = max_y - min_y
    scale = min(width / vw, height / vh) * 0.8

    def tx(x):
        return (x - min_x) * scale + (width - vw * scale) / 2

    def ty(y):
        return (y - min_y) * scale + (height - vh * scale) / 2

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}"'
        f' viewBox="0 0 {width} {height}" style="background:#1a1a2e;">',
        f'<text x="{width / 2}" y="25" text-anchor="middle" fill="white"'
        f' font-family="monospace" font-size="14">{part}: NPTH Edge.Cuts</text>',
    ]

    # Old polygon (red dashed)
    if old_pts:
        d = "M " + " L ".join(f"{tx(x):.1f},{ty(y):.1f}" for x, y in old_pts) + " Z"
        lines.append(
            f'<path d="{d}" fill="rgba(255,68,68,0.15)" stroke="#ff4444" stroke-width="2" stroke-dasharray="6,4"/>'
        )

    # New polygon (green solid)
    if new_pts:
        d = "M " + " L ".join(f"{tx(x):.1f},{ty(y):.1f}" for x, y in new_pts) + " Z"
        lines.append(f'<path d="{d}" fill="rgba(68,255,68,0.1)" stroke="#44ff44" stroke-width="2"/>')

    # Vertex dots
    for x, y in new_pts:
        lines.append(f'<circle cx="{tx(x):.1f}" cy="{ty(y):.1f}" r="2" fill="#44ff44" opacity="0.6"/>')
    for x, y in old_pts:
        lines.append(f'<circle cx="{tx(x):.1f}" cy="{ty(y):.1f}" r="4" fill="#ff4444" opacity="0.8"/>')

    # Legend
    ly = height - 40
    lines.append(
        f'<line x1="20" y1="{ly}" x2="50" y2="{ly}" stroke="#ff4444" stroke-width="2" stroke-dasharray="6,4"/>'
    )
    lines.append(
        f'<text x="55" y="{ly + 4}" fill="#ff4444" font-family="monospace"'
        f' font-size="11">Before fix ({len(old_pts)} pts)</text>'
    )
    lines.append(f'<line x1="20" y1="{ly + 18}" x2="50" y2="{ly + 18}" stroke="#44ff44" stroke-width="2"/>')
    lines.append(
        f'<text x="55" y="{ly + 22}" fill="#44ff44" font-family="monospace"'
        f' font-size="11">After fix ({len(new_pts)} pts)</text>'
    )
    lines.append("</svg>")
    return "\n".join(lines)
